### ISSUE TITLE
Calling For Release Testers - Please Help!

### ISSUE THREAD

**Issue by NoMoreFood** [windirstat/windirstat#145]
All,

I've got some more significant changes in store for the next major version (e.g., NTFS MFT scanning) so I'd like to release 2.1 before I start integrating those changes.  If anyone can download the latest pre-release (https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-12-07) and verify that it's working properly, I would really appreciate it.  Either reply or react to this post if you tested and things look good. Thanks!

EDIT: Link Updated 2024-12-07

**Comment by NoMoreFood** [comment]
Past contributors would really appreciate any assistance you can provide and thank you for continued support.  Thanks!  @AartBluestoke, @aboe026, @achtchaern, @aglpy, @Antonimo-Dev, @Anutrix, @ARMcompat, @Asinin3, @assarbad, @atsju, @Avaruz, @az64x, @Baardi, @berkayfeci, @BiatuAutMiahn, @blyamur, @Burger23333, @cars11, @DanielRouxSA, @DaveG-SDX, @driscoll42, @duaneellissd, @EricPossato, @erikblake, @FeralHedgehog, @fomox, @FuzzyRick, @georgir, @Gerbilnut, @greuwer, @GuyLarri, @HenryGessau, @Hoaas, @hueldoeu, @hypesquare, @imthenachoman, @irzyxel, @jamesaepp, @jeverett-syl, @jhv2017kam, @JonBeeTheThird, @Julio860JVL, @JustinJayL, @kaala, @Kbdq, @linuxgurugamer, @Lockszmith-GH, @MatthewSteeples, @Max-RM, @Medowar, @Melvalg, @mrplumber, @mywebguytaylor, @Neustradamus, @nitz, @NoMoreFood, @nordbymikael, @nsummy, @ntman1, @PC-SPEZIALIST, @PedroBittarBarao, @PEERSOFTdev, @piotr-kubiak, @RandyInHawaii, @RB2982, @rdp, @regs01, @reukiodo, @RFBomb, @richard987, @rnmerchant, @RobertK66, @Rockz1152, @salvis, @seangibbz, @SimonLarsenCFM, @sitiom, @Six0Ne, @Skippz88, @squeak9, @srt54558, @svenbolte, @tenehea, @TenkenNoSoujiro, @tferrerm, @theonlyames, @ThoughtPhotography, @TilKenneth, @tron2k, @Twincam99, @UweTrottmann, @vittoso, @vlakoff, @vonswoopington

**Comment by NoMoreFood** [comment]
Past contributors would really appreciate any assistance you can provide and thank you for continued support.  Thanks!  @Melvalg, @mrplumber, @mywebguytaylor, @Neustradamus, @nitz, @NoMoreFood, @nordbymikael, @nsummy, @ntman1, @PC-SPEZIALIST, @PedroBittarBarao, @PEERSOFTdev, @piotr-kubiak, @RandyInHawaii, @RB2982, @rdp, @regs01, @reukiodo, @RFBomb, @richard987, @rnmerchant, @RobertK66, @Rockz1152, @salvis, @seangibbz, @SimonLarsenCFM, @sitiom, @Six0Ne, @Skippz88, @squeak9, @srt54558, @svenbolte, @tenehea, @TenkenNoSoujiro, @tferrerm, @theonlyames, @ThoughtPhotography, @TilKenneth, @tron2k, @Twincam99, @UweTrottmann, @vittoso, @vlakoff, @vonswoopington

**Comment by AartBluestoke** [comment]
I'll give it a go, but i'm overseas with limited time this week.

**Comment by AartBluestoke** [comment]
first feedback is google flags it as suspicious:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/d48dcdf1-bd18-484d-925a-dcc6aabd4b72">
but it passes the scan
<img width="372" alt="image" src="https://github.com/user-attachments/assets/446f9f92-3916-43e3-9f0a-18ee72cf06a5">


it took 56 seconds, mostly on the C drive, where once the other drives completed, it ran a burst, then paused, and continued again rather than smoothly incrementing.
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/7b0f0f8c-74d0-4807-afa8-c280b601cef6">
This was with 10 threads.
a rescan with 16 threads only took 18 seconds, presumably hitting cached data that stalled the first one?
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/147ef056-08e8-48a4-8de7-7029495d8267">

This was not run in admin mode, just local user mode. I have google drive and onedrive, and it tallied the size of the google drives, but not the onedrive.
I didn't see the option for 'on-disk' size vs 'actual size' that was there before?

**Comment by NoMoreFood** [comment]
@AartBluestoke Is the OneDrive the item that's showing up as 65.5 KB?  I have OneDrive but it just shows up as a subdirectory in my user profile.  Is that any different from how WinDirStat 2.0.3 was displaying it?  Might be something I want to look into, but want to make sure we're not making it any _worse_ moving from 2.0.3 to 2.1.

The "on-disk" versus "actual size" I believe is the "Logical Size" versus "Physical Size".

Thanks for testing!

**Comment by rnmerchant** [comment]
Downloaded, installed and ran the beta on my Lenovo Thinkpad Carbon X1 Intel system with Win10 22H2.
It opened fine and I was just pointing around on the screen and I had a sudden disappearance (= crash, I suppose) of the program.  I couldn't find a log file that looked like it belonged to this
I ran the program a second time and again it opened fine.   I moved around as before within the program window and I could not repeat the crash....   So this isn't very helpful at this point but I shall keep looking.

Cheers R

**Comment by Max-RM** [comment]
It looks like I'm only Windows ARM tester here, so I found several errors.

If try to install ARM32 installer on ARM64 Windows 11 with ARM64 CPU tgen installer will say that "not supported by this processor type" ALTHOUGH it's NOT!
Because I tested portable ARM32 exe (without installer) on this device and it worked perfectly.
(Many ARM64 CPUs has backward ARM32-bit compability, same as x64 CPU do with x86 support).

ARM64 installer doesn't allow me to select "D:" drive to install, so I did it via paste full path into window, and then it takes about 5 minutes to install (seriously? 5 mins to extract just one 4,5 mb file?)

So I think it will be better to distribute ARM32 and ARM64 versions of WinDirStat in release page in form of archive that will contain not only installer, but portable exe too to avoid those problems above.

**Comment by NoMoreFood** [comment]
@Max-RM Thanks. The 5 minute wait is probably due to a timeout.  There is some code in there to execute the uninstaller for the 1.x version and then wait for the files to disappear.  Something about ARM must have been throwing off that check.  I will look into it.  Thanks!

**Comment by RobertK66** [comment]
No probs found at all here with Windows 11 Pro 23H2 and using the std x64 version.
- Played around a little with&without admin rights. Looking for Unknown and System dirs.
- My Sym linked drive worked with both settings ignore/include.

**Comment by driscoll42** [comment]
Running on Windows 10 with two SSDs, four HDDs, a USB Drive, and Google Drive, all worked fine, took 1:48 with 16 threads. But no issues at all. Installed with the msi installer not in admin mode.

**Comment by PC-SPEZIALIST** [comment]
I installed the WinDirStat-x64.msi silently using the _/qn_ parameter from [N-able N-SIGHT RMM](https://www.n-able.com/products/n-sight-rmm) on a Windows 11 Pro (build 22631) workstation with a single internal SSD and did not notice any issues so far. You are awesome!

**Comment by linuxgurugamer** [comment]
Installed on my system, did a scan of my C drive, went well.
Did a scan of my pictures with duplicate files turned on, also went well (depressing how many dups I have).  Doing a full duplicate scan on my D drive (about 1.5 tb of data) is taking a lot longer

**Comment by DaveG-SDX** [comment]
I just downloaded the portable version a few minutes ago which are the versions I use most of the time. I'm a bit limited on time since I have a lot to catch up after coming back from "staycation" (stay home vacation). If there is anything specific you want to see tested then please let me know. I will report back on whatever else I find, but it is looking good so far!!! My primary interest in the utility is so that I can compare the files physically on my machine separate from those that are not.

I have OneDrive in our company mahcine. What I can see immediately after comparing the current version I have (v2.0.3) and the new v2.1.0 is that the Physical and Logical drives are now reporting correctly on the new version. In the old version had these  two totals reversed. 

The screenshot below shows a parent folder which contains two subfolders. The "Avanquest Driver Genius" subfolder is physically downloaded on the machine. The "Visioneer OneTouche 7400 USB Scanner" subfolder is only in the cloud.

![explorer_2024-12-03_11-20](https://github.com/user-attachments/assets/b5e8d75f-da9e-4351-b8c0-26fa461e30b6)

By the way ... As my feature request ... It would be great if you could add a status icon to tell at a glance if the file is local, temporary local, or in the cloud.  In addition, a way to filter out of the view, those that are not physically on the machine so that we can have a view of only those files that are physically occupying space on the machine.

Great job. Love the tool.

My computer specs:
Windows 10 22H2
Lenovo ThinkPad P72

**Comment by Burger23333** [comment]
Beta installed fine. I cannot test my original issue, a very large Unknown Folder, since this folder has been successfully removed- and has not come back.

Thanks for all your work on a great product.

 

Chris

**Comment by tron2k** [comment]
@NoMoreFood 
I can reproduce a crash.
- Scan C:
- Press F6 (or F7 ) several times in succession
- WinDirstat crashes

I noticed that the percentage display increases after each F6 press.
First scan:
![image](https://github.com/user-attachments/assets/1ebd982d-0c3d-4954-94d9-0a13770dd24b)
After pressing F6 a few times:
![image](https://github.com/user-attachments/assets/5246e6f6-a938-4ef4-87cf-9e4b8cf9c99d)

**Comment by BiatuAutMiahn** [comment]
Installed, Ran, did Scan (took less than a minute), Reset prefs, restarted, ran again (completed in less than 30s), as soon as I tried to expand (C:) is hung and stayed hung while reading through this thread and typing this msg. Going to kill and try other things.

**Comment by BiatuAutMiahn** [comment]
On next run again completed in seconds, left treemap open and everything works as expected, back arrow functionality is fixed now too :) The delete dialog /w progress is nice to see back as well and even better than legacy it doesn't double prompt. (not sure if that's on purpose). Now that I think of it the "Do not show this again" prompt for delete could be a radio for either "never again" (configurable via options) and a "for this session". Also, (this may just be a nit) but the in windows the file op dialog defaults focus on the "ok/yes" button and escape cancels, so when its default on no in this app it messes with our muscle memory (for those of us who that applies to anyhow)

**Comment by Neustradamus** [comment]
Dear @windirstat team, @NoMoreFood,

Thanks for your work!

I have seen a problem, the old original latest version is not removed with the new install, it is important to add it!

Thanks in advance.

**Comment by NoMoreFood** [comment]
@Neustradamus  With the "Beta" versions versus production releases, this is expected since they have their own MSI heritage.  Sorry, I should have mentioned that.  Users who stick to the production versions will have it removed.  Thanks for testing!

**Comment by NoMoreFood** [comment]
@BiatuAutMiahn Thanks for the feedback.  I will look into the things you mentioned.  I will look into overlays for the next version.  I like the idea.  Right now, we have no hardlink support, but after I add MFT scanning, we will.

**Comment by NoMoreFood** [comment]
@tron2k Yeah, I can see what's going on there.  Has to do with some of the threading to asynchronously fetch shell icons.  I will see if I can safely fix it.  Thanks for testing!

**Comment by Neustradamus** [comment]
@NoMoreFood: I speak about 1.1.2 (not the 2.0.3), the installer must remove previous, please look for it...

**Comment by NoMoreFood** [comment]
@Neustradamus Oh, there is logic in there to do that.  I will try to reproduce that.  Thanks!

**Comment by Max-RM** [comment]
> @Max-RM Thanks. The 5 minute wait is probably due to a timeout. There is some code in there to execute the uninstaller for the 1.x version and then wait for the files to disappear. Something about ARM must have been throwing off that check. I will look into it. Thanks!

What about other problems?

**Comment by hueldoeu** [comment]
i can see that windirstat v2 started not much time ago in october 2024. i have installed windirstat before that month and i just used it to discover the "big files" i can delete so that i can download more stuff. according to this https://en.wikipedia.org/wiki/WinDirStat#Version_history at least 10 years the development of windirstat has nearly stopped from around 2007 until 2024 and i would like to know what's the reason to start with a new branch or version.

i was satisfied with windirstat v1.

**Comment by linuxgurugamer** [comment]
> i can see that windirstat v2 started not much time ago in october 2024. i have installed windirstat before that month and i just used it to discover the "big files" i can delete so that i can download more stuff. according to this https://en.wikipedia.org/wiki/WinDirStat#Version_history at least 10 years the development of windirstat has nearly stopped from around 2007 until 2024 and i would like to know what's the reason to start with a new branch or version.
> 
> i was satisfied with windirstat v1.

Actually, the first beta release was in October.  If you look at the commit history,  there have been continual commits over the years, it looks like activity picked up at the beginning of this year.  I'll leave the reasons to the author, just wanted to make sure you realized that this has been in development for a much longer time

**Comment by salvis** [comment]
I like your presentation of the subst'ed drive F:
![image](https://github.com/user-attachments/assets/9bd314c8-e807-4ec5-9a2a-2c64a8ec7402)

I opened drive F: only, clicked on some files and extensions, then File|Select network drive T: only, and after 4 seconds of scanning the Beta disappeared. This is reproducible, also with D: only and G: only. I find no error information.

**Comment by salvis** [comment]
There is some confusion about the drive S: in my comment above. Not just in WinDirStat, but foremost in Windows 10 22H2:

![image](https://github.com/user-attachments/assets/05988878-03be-4a82-a43a-06a719f3f122)

Windows has assigned drive S: to an SD Card as well as to a network share! It's showing a mixture of the device properties (share usage and SD Card icon, and the SD Card files, not on the screenshot) in Windows Explorer. WinDirStat OTOH shows the properties of the SD Card (screenshot in my comment above). Anyway, this is BS, and no need to do anything about it in WinDirStat. If anything, WinDirStat is more correct.

After ejecting/disconnecting both and mounting/connecting both again, things look more reasonable, with the SD Card showing up as drive H:

![image](https://github.com/user-attachments/assets/28cd65d8-f01a-4253-91fb-30aa63b21784)

The SD Card has no volume label and Windows displays "Removable Disk" instead. WinDirStat displays nothing, just "<space>(S:)" (above), which is not so nice (fix desirable).

WinDirStat now shows this (I gave the SD Card a volume label in the meantime):

![image](https://github.com/user-attachments/assets/5eb00dd8-41cc-4e4d-8d73-23331db45b69)

What we notice here;

- WinDirStat has refreshed the share name of drive S:, but not the drive icon (should be fixed).
- Unlike Windows, WinDirStat is not showing the device name, obscuring the fact that S: and T: are shares on the same device (fix desirable).
- Neither Windows nor WinDirStat are showing the SD Card icon for drive H: (never mind, probably OK after a reboot).

**Comment by reukiodo** [comment]
2.1 seems substantially faster than the 2.0 build I was using previously.

**Comment by rdp** [comment]
first: i kinda expected the .msi to have a checkbox at the end "run windirstat" :) (or create a desktop icon?)
second: help -> help just goes to the description?
third: #135 doesn't seem fixed...

That's it, cheers!

**Comment by NoMoreFood** [comment]
@tron2k I identified the cause of the crash you reported it and committed a fix for it.   Thanks!

**Comment by NoMoreFood** [comment]
@salvis Thank you for the report. I will probably investigate those post 2.1.

**Comment by NoMoreFood** [comment]
@Max-RM  I changed the uninstall behavior so it should not incur a long delay like you saw.  As for the ARM installer saying processor not supported on ARM64, I do not know what that's occurring and honestly my it's intolerably slow to debug on my QEMU instance of Windows ARM64.  It's possible that it would run fine on a native 32-bit Windows ARM build so it would be break if someone with one of those platforms was available to test.  The important thing is that the 64-bit version of it worked on Windows ARM64 (less the slow behavior that you noted and should be fixed in the next release).

I plan to update the webpage after the release.

**Comment by NoMoreFood** [comment]
@Neustradamus I've revised the installer so the old version should now be more reliably uninstalled.

**Comment by Max-RM** [comment]
> if someone with one of those platforms was available to test. 
>
I will get Surface RT with Windows 10 ARM32 (leaked build) very soon.

**Comment by NoMoreFood** [comment]
I just released https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-12-07 that to address to two crashing scenarios and one installer issue.  I will be creating separate issues for the various feature requests or pre-existing issues that some of you had reported.

**Comment by tron2k** [comment]
> @tron2k I identified the cause of the crash you reported it and committed a fix for it. Thanks!
@NoMoreFood 
Unfortunately, the bug is still existing in the new version.

**Comment by NoMoreFood** [comment]
@tron2k Can you clarify on the behavior you are seeing?

**Comment by tron2k** [comment]
> @tron2k Can you clarify on the behavior you are seeing?
I've just had another look at it. To check whether the bug has been fixed, I quickly pressed F6 one after the other. 
But in practice, nobody will do that.

**Comment by NoMoreFood** [comment]
@tron2k  Weird.  You are certainly correct that it's not something most folks are likely to do, but I hate bugs.  I definitely was able to reproduce it before and now I can't.  It was basically because caused by the fact that the freespace node was getting removed while graph was in the middle of recalculating.  Can you doubly verify that you're running the 2024-12-07 version in the About box?

**Comment by hueldoeu** [comment]
> > @tron2k Can you clarify on the behavior you are seeing?
> > I've just had another look at it. To check whether the bug has been fixed, I quickly pressed F6 one after the other.
> > But in practice, nobody will do that.

plz try to quote better like

>@tron2k Can you clarify on the behavior you are seeing?

I've just had another look at it. To check whether the bug has been fixed, I quickly pressed F6 one after the other.
But in practice, nobody will do that.

**Comment by NoMoreFood** [comment]
I'm going to go ahead and publish this release since nothing critical has been identified.  For anyone that can still reproduce an issue on the official release, please open an issue.  I really appreciate everyone who jumped on to test!

**Comment by Neustradamus** [comment]
@NoMoreFood: Thanks!
But there is a missing part to remove (there is an option in windirstat1_1_2_setup.exe:
- C:\ProgramData\Microsoft\Windows\Start Menu\Programs\WinDirStat
- C:\Users\USER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\WinDirStat

Can you add details in Installer?
Example in one installer project: https://www.advancedinstaller.com/user-guide/product-details-tab.html

In Control Panel/Programs
- Name
- Publisher
- Version
- Comments
- Contact
- Readme File
- Update Info Link
- Help Link
- Technical Support Link
- Support Phone (I think it is not needed)

Some softwares add the information of Windows too:
- Registered Owner
- Registered Company

**Comment by salvis** [comment]
The 12/07 version is still crashing for me as described above.

**Comment by NoMoreFood** [comment]
@salvis Yeah, I couldn't reproduce that.  If you could see if a .dmp file is created with 2.1.1, and email it to me (berns@uwalumni.com), I would appreciate it.

**Comment by hueldoeu** [comment]
> e certainly correct that it's not something most folks are likely to do, but I hate bugs. I definitely was able to reproduce it before and now I can't. It was basically because caused by the fact that the freespace node was getting removed while graph was in the middle of recalculating. Can you doubly verify that you're running the 2024-12-07 version in the About box? I'm going to go ahead and proceed with the

just in case you want to know, i edited unigetUI this way that every 2 hours it checks available updates. now it's 00:25 AM UTC 9th Dec 2024 and the newest version of windirstat (2024-12-07) probably about midnight UTC had been installable through winget. it could be around 24 hours until updates can be installed and are downloadable through winget.

**Comment by reukiodo** [comment]
After installing the release 2.1.1 I experienced a crash while browsing through the tree (win11 arm64) but I could not reproduce, and I don't see any .dmp file anywhere.

**Comment by erikblake** [comment]
Install worked fine, and was able to log the contents of my Android phone via a wifi link to a WebDav server on the phone, which was linked to a mapped drive on my PC. This version resolves the issue with #118

**Comment by NoMoreFood** [comment]
@salvis  Can you try this build? https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.2/2024-12-10  Thanks!

**Comment by hueldoeu** [comment]
got the mail for windirstat v2.1.2 at 2:36 PM UTC and i lowered the
sync-time of unigetUI to 10 min just for this test and right now at 8:34 PM
UTC the update had been downloaded and installed (auto install is enabled).

Am Di., 10. Dez. 2024 um 15:38 Uhr schrieb Bryan Berns <
***@***.***>:

**Comment by Max-RM** [comment]
> @salvis Can you try this build? https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.2/2024-12-10 Thanks!

It works on Surface RT on Windows 10 ARM32 (leaked build).

**Comment by Max-RM** [comment]
> out of curiosity: can you make screenshots on it with windows-key + shift + s?

looks like yea. But Idk where is screenshot located now.

**Comment by hueldoeu** [comment]
> > out of curiosity: can you make screenshots on it with windows-key + shift + s?
> 
> looks like yea. But Idk where is screenshot located now.

it's in the clipboard

**Comment by Max-RM** [comment]
> > > out of curiosity: can you make screenshots on it with windows-key + shift + s?
> > 
> > 
> > looks like yea. But Idk where is screenshot located now.
> 
> it's in the clipboard

Ок

**Comment by AartBluestoke** [comment]
feature request, deduplication:
default "well-known duplicates" are ignored
- eg, anything in the steamapps folder, which you have no control over.
- things in the recyle bin
- There isn't much i can do to resolve this duplication, and deleting this would break one of those folders.
<img width="683" alt="image" src="https://github.com/user-attachments/assets/83519bb2-4ee4-4708-89af-a5cc9f1cd35b" />
<img width="569" alt="image" src="https://github.com/user-attachments/assets/64540080-7d71-43ee-b60e-ca70bb1163cf" />

- some folders have many duplicates, it would be nice to roll up those into a common folder by default - i don't need to be individually informed of every Windows Foundation DLL in these folders (there's a few ...)
<img width="524" alt="image" src="https://github.com/user-attachments/assets/99487bf4-47b6-476b-b0cc-bc19e3cac89f" />
- addendum (this post was in draft for a while) - this gets quite slow when scanning a large folder, there is a non-linear algorithm in there somewhere, perhaps in the hash comparison:
<img width="421" alt="image" src="https://github.com/user-attachments/assets/8e6b4c6f-892e-4bfe-abca-ad1b3c2745db" />

**Comment by AartBluestoke** [comment]
the speed may be because of the inserts into the duplicate lists:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/2fd2b6f9-aef2-4c0a-86be-80d62dda81a7" />
this is continually updating for me, roughly in the same frequency as the stutters in the 'pac man'

Perhaps limit the display size to > 1mb while searching, with just some course stats of 'dupes smaller than 1m, 100k, 10k, 2k' or something?

**Comment by NoMoreFood** [comment]
@AartBluestoke  I will take a look at it.  It I think insertion into the list (which can trigger a sorting algorithm), may be a good places to start.

**Comment by linuxgurugamer** [comment]
> @AartBluestoke I will take a look at it. It I think insertion into the list (which can trigger a sorting algorithm), may be a good places to start.

Another thing, you may want to limit the sorting to a time period.  I found the duplicate search to be useless and mentioned this 2 weeks ago.  If, instead of sorting every time, you sort based on a time period of between once a second and once every 30 seconds (based on how many items are there to be sorted), you should be able to improve the performance.  If duplicates are found during the sort, you can merge them at that time.

I'm also curious as to why you are using a list instead of some sort of index algorithm.  I realize the list is faster to code, but the index might be better performance, depending on how you code it

**Comment by NoMoreFood** [comment]
@linuxgurugamer Thanks, I am literally testing deferred sorting right now (which is what I do for the normal, non-dupe view).

**Comment by AartBluestoke** [comment]
If you stop the duplicate check, (as i did after 9 hours running, lol) it doesn't show the size - sum of 0. - also, showing the size wouldn't be clear if that is the size of all duplicates, the amount that would be saved, or the base size of the singles that have replicas (all 3 numbers would be nice, especially on a folder path basis)
<img width="702" alt="image" src="https://github.com/user-attachments/assets/8d0b2408-0a90-4f07-ba86-9a415715bfe1" />
