### ISSUE TITLE
Bug Report: Fast Volume Scan Support related issues

### ISSUE THREAD

**Issue by harryytm** [windirstat/windirstat#264]
Crash and exit without error message when running WinDirStat 2.3.1 as Administrator

Visual Studio have the following debug output for mutex:15

```
Exception thrown: read access violation.
**mtx** was 0xC4F26DCF20.
```

Seems like some new codes unable lock read access to the drive causing the problem.
Even with some drive managed to lock read access, the size reported in many files are incorrect.

**Comment by NoMoreFood** [comment]
Yes, that commit is a pretty big change and I'm still working through some of the implementation.  I'll let you know when to try again.

**Comment by harryytm** [comment]
MFT Accelerated Volume Scan Support is a big leap forward, keep up the good job.

I would suggest an option for user to choose which scanning engine to use, preferability located in the Select Drives dialog just as "Scan for duplicate file", and fallback to basic scanner when failed to gain access lock, for intuitive and streamline user experience.

**Comment by NoMoreFood** [comment]
I agree with your recommendation on providing it as an option.  Do you have any idea what specific line of code you were seeing failures on?

**Comment by harryytm** [comment]
> I agree with your recommendation on providing it as an option. Do you have any idea what specific line of code you were seeing failures on?

the following is the call stack

```
 	WinDirStat_x64.exe!mtx_do_lock(_Mtx_internal_imp_t * mtx, const _timespec64 * target) Line 79	C++
>	[Inline Frame] WinDirStat_x64.exe!std::_Mutex_base::lock() Line 52	C++
 	[Inline Frame] WinDirStat_x64.exe!std::lock_guard<std::mutex>::{ctor}(std::mutex &) Line 445	C++
 	[Inline Frame] WinDirStat_x64.exe!getMapBinRef(std::unordered_map<unsigned __int64,unsigned __int64,std::hash<unsigned __int64>,std::equal_to<unsigned __int64>,std::allocator<std::pair<unsigned __int64 const ,unsigned __int64>>> * mapArray, std::mutex * key, unsigned __int64 binSize, unsigned __int64) Line 165	C++
 	WinDirStat_x64.exe!`FinderNtfsContext::LoadRoot'::`2'::<lambda_1>::operator()<std::pair<unsigned __int64,unsigned __int64>>(const std::pair<unsigned __int64,unsigned __int64> & dataRun) Line 272	C++
 	[External Code]	
```

of the exception thrown in mutex on line 52

```
Exception thrown: read access violation.
**mtx** was 0x572E3F0A10.
```

**Comment by harryytm** [comment]
Another major issues is the physical file size of the scan, nearly 16% of the physical size fallen into Unknown, which in my case is 759.9GiB of 4.6TiB, all files that have Alternate Data Stream(This file came from another computer and might be blocked) have incorrect size of 26 Bytes on the tree list.

**Comment by NoMoreFood** [comment]
As for the crash, can you see if the latest commit fixes it?  I'm looking in the size next.

**Comment by NoMoreFood** [comment]
I believe I've also addressed the alternate data stream issue. I'm sure there are some other size issues I still need to work through yet. Please let me know anything else you can find.

**Comment by harryytm** [comment]
> As for the crash, can you see if the latest commit fixes it? I'm looking in the size next.

Not resolve yet, same unhandled exception and call stack.
Might be a good idea look into FinderNtfs.cpp:272
or make use of Volume Snapshot Service? just a weird idea I came up might not work.

**Comment by harryytm** [comment]
> I believe I've also addressed the alternate data stream issue. I'm sure there are some other size issues I still need to work through yet. Please let me know anything else you can find.

size issues resolved by d188cbeccb9e823e782691eb94ab60b6f354aebc

**Comment by NoMoreFood** [comment]
> > As for the crash, can you see if the latest commit fixes it? I'm looking in the size next.
> 
> Not resolve yet, same unhandled exception and call stack. Might be a good idea look into FinderNtfs.cpp:272 or make use of Volume Snapshot Service? just a weird idea I came up might not work.

It's not a volume locking issue.  It has to do with mutex bins I have to reduce inter-thread contention -- I must still have a math error.

**Comment by NoMoreFood** [comment]
> > As for the crash, can you see if the latest commit fixes it? I'm looking in the size next.
> 
> Not resolve yet, same unhandled exception and call stack. Might be a good idea look into FinderNtfs.cpp:272 or make use of Volume Snapshot Service? just a weird idea I came up might not work.

Can you confirm this is still an issue with the more recent commits?

**Comment by harryytm** [comment]
> > Not resolve yet, same unhandled exception and call stack. Might be a good idea look into FinderNtfs.cpp:272 or make use of Volume Snapshot Service? just a weird idea I came up might not work.
> 
> Can you confirm this is still an issue with the more recent commits?

Issue resolved by 73ec2b5502d47c86472d4f199380460a0e29032d
The drive scan is blazing fast!

**Comment by NoMoreFood** [comment]
Awesome.  Thank you for confirming and the feedback.  I still need to add in logic to address various types of hardlinks better and have a bunch of small bugs to work out, but I am happy with the new scan.

For the date in the future... can you drill down and see if that's coming from a particular file?

**Comment by harryytm** [comment]
> Awesome. Thank you for confirming and the feedback. I still need to add in logic to address various types of hardlinks better and have a bunch of small bugs to work out, but I am happy with the new scan.
> 
> For the date in the future... can you drill down and see if that's coming from a particular file?

Minor anomaly:
- [ ] - Last Change for some drives and "This Computer" is the date in 2094-08-18 03:36
- [x] - The text of "This Computer" , "Free Space" and "Unknown" entries always blue in color

<img width="1070" height="903" alt="Image" src="https://github.com/user-attachments/assets/27a81013-fec9-4fdf-b410-665a740a959f" />

**Comment by harryytm** [comment]
> I would suggest an option for user to choose which scanning engine to use, preferability located >in the Select Drives dialog just as "Scan for duplicate file", and fallback to basic scanner when failed to gain access lock, for intuitive and streamline user experience.
>> I agree with your recommendation on providing it as an option.

Implemented with commit c424ab381bfd1b8ff5f471011105f2954b8c9916
Tested working normal.

**Comment by harryytm** [comment]
> The text of "This Computer" , "Free Space" and "Unknown" entries always blue in color

Issue resolved by 2400d433e8caadbf2233ad4a12250cd152abc2e8

<img width="1153" height="389" alt="Image" src="https://github.com/user-attachments/assets/8b596022-7242-44ab-84fd-f18257a764bc" />

**Comment by harryytm** [comment]
Select Drive undesirable behaviors issues possibility after 68f464960832c1122c659f60b73c1262e3b19bf0, when selecting individual drives in the drives list, "Use enhanced scanning engine (requires elevated privileges)" options would check/uncheck according to the last scan status, unless changing this option to desire status and then click OK or press Enter on the keyboard.

**Comment by harryytm** [comment]
Here is a proposed logic flow for Elevation Prompt to reduce annoyance of the Elevation Prompt on unelevated start for a more streamlined user experience.

"Enable/Disable FastScanEngine" means Check/Uncheck "Use enhanced scanning engine (requires elevated privileges)" option
"UseFastScanEngine" means the preference setting saved in user preference(UseFastScanEngine in registry or ini)

```mermaid
flowchart TD;
A([Start])-->B{Elevated privileges?};
B-- True -->C(Select Drives Dialog);
B-- False -->D{UseFastScanEngine?};
C-->StartScan[/Start Scan/];
D-- True --> E(Elevation Prompt);
D-- False --> C;
E-->Y[/Yes/]-->F[Enable UseFastScanEngine]-->G[Restart in elevated]-->A;
E-->N[/No/]-->H[Disable UseFastScanEngine]-->C;
C-->K[/Enable UseFastScanEngine/]-->I{Elevated privileges?}-- False -->E;
I-- True -->J[Enable UseFastScanEngine]-->C;
```

**Comment by harryytm** [comment]
> Select Drive undesirable behaviors issues possibility after [68f4649](https://github.com/windirstat/windirstat/commit/68f464960832c1122c659f60b73c1262e3b19bf0), when selecting individual drives in the drives list, "Use enhanced scanning engine (requires elevated privileges)" options would check/uncheck according to the last scan status, unless changing this option to desire status and then click OK or press Enter on the keyboard.

Tested issue resolved by 827d780414c8813a92df729b8442198431072640

**Comment by harryytm** [comment]
Here is the unofficial preview build for those who interested in testing latest commit 800c5792e3760f72a746e7970d80b63cfc806dc7

!!!!! USE IT AT YOUR OWN RISK !!!!!

https://github.com/harryytm/windirstat/releases/tag/preview-upstream-master-800c5792e3760f72a746e7970d80b63cfc806dc7

**Comment by NoMoreFood** [comment]
@harryytm  Thank you for providing this interim build. I just published a new pre-release.  Is there anything in this list still unresolved? My next plan is to address the hard linked files and cleaning up some of the anomalies related to certain reparse point types.

**Comment by harryytm** [comment]
@NoMoreFood I am very happy with the latests build, really love the Fast Volume Scan which make the drive scan blazing fast as a dream, and the search function is yet another useful feature I love, thanks for your effort to implement that, appreciate your good work.
